[tox]
requires =
    tox-uv >= 1.33.4
env_list =
    pre-commit
    py{311,312,313,314}
    docs

[testenv]
package = wheel
dependency_groups = test
commands =
    pytest -n=auto tests/

[testenv:py314]
commands =
    pytest -n=auto --cov=backtide --cov-report=xml tests/

[testenv:pre-commit]
skip_install = true
dependency_groups = pre-commit
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
skip_install = true
dependency_groups = docs
commands =
    mkdocs build --strict
