//! ISO 4217 currency definitions.

use pyo3::pyclass;
use serde_with::{DeserializeFromStr, SerializeDisplay};
use strum::{Display, EnumString};

/// An ISO 4217 currency tied to a specific country or supranational union (e.g., EUR).
///
/// Variant names are identical to their 3-letter ISO codes, so [`std::str::FromStr`]
/// and [`std::fmt::Display`] round-trip losslessly.
#[pyclass(from_py_object)]
#[derive(
    Clone,
    Copy,
    Debug,
    Default,
    Eq,
    Hash,
    PartialEq,
    Display,
    EnumString,
    SerializeDisplay,
    DeserializeFromStr,
)]
#[strum(ascii_case_insensitive)]
pub enum Currency {
    AED,
    AFN,
    ALL,
    AMD,
    AOA,
    ARS,
    AUD,
    AZN,
    BAM,
    BDT,
    BGN,
    BHD,
    BND,
    BOB,
    BRL,
    CAD,
    CHF,
    CLP,
    CNY,
    COP,
    CRC,
    CZK,
    DKK,
    DOP,
    DZD,
    EGP,
    #[default]
    EUR,
    FJD,
    GBP,
    GEL,
    GHS,
    GTQ,
    HKD,
    HNL,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KRW,
    KWD,
    KYD,
    KZT,
    LBP,
    LKR,
    LYD,
    MAD,
    MDL,
    MKD,
    MNT,
    MOP,
    MUR,
    MVR,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SCR,
    SEK,
    SGD,
    SRD,
    THB,
    TND,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    UYU,
    UZS,
    VND,
    YER,
    ZAR,
    ZMW,
}

impl Currency {
    fn data(&self) -> (&'static str, &'static str, &'static str, u8) {
        use Currency::*;
        match self {
            AED => ("United Arab Emirates dirham", "United Arab Emirates", "🇦🇪", 2),
            AFN => ("Afghan afghani", "Afghanistan", "🇦🇫", 2),
            ALL => ("Albanian lek", "Albania", "🇦🇱", 2),
            AMD => ("Armenian dram", "Armenia", "🇦🇲", 2),
            AOA => ("Angolan kwanza", "Angola", "🇦🇴", 2),
            ARS => ("Argentine peso", "Argentina", "🇦🇷", 2),
            AUD => ("Australian dollar", "Australia", "🇦🇺", 2),
            AZN => ("Azerbaijani manat", "Azerbaijan", "🇦🇿", 2),
            BAM => ("Bosnia and Herzegovina convertible mark", "Bosnia and Herzegovina", "🇧🇦", 2),
            BDT => ("Bangladeshi taka", "Bangladesh", "🇧🇩", 2),
            BGN => ("Bulgarian lev", "Bulgaria", "🇧🇬", 2),
            BHD => ("Bahraini dinar", "Bahrain", "🇧🇭", 3),
            BND => ("Brunei dollar", "Brunei", "🇧🇳", 2),
            BOB => ("Boliviano", "Bolivia", "🇧🇴", 2),
            BRL => ("Brazilian real", "Brazil", "🇧🇷", 2),
            CAD => ("Canadian dollar", "Canada", "🇨🇦", 2),
            CHF => ("Swiss franc", "Switzerland", "🇨🇭", 2),
            CLP => ("Chilean peso", "Chile", "🇨🇱", 0),
            CNY => ("Chinese yuan", "China", "🇨🇳", 2),
            COP => ("Colombian peso", "Colombia", "🇨🇴", 2),
            CRC => ("Costa Rican colon", "Costa Rica", "🇨🇷", 2),
            CZK => ("Czech koruna", "Czech Republic", "🇨🇿", 2),
            DKK => ("Danish krone", "Denmark", "🇩🇰", 2),
            DOP => ("Dominican peso", "Dominican Republic", "🇩🇴", 2),
            DZD => ("Algerian dinar", "Algeria", "🇩🇿", 2),
            EGP => ("Egyptian pound", "Egypt", "🇪🇬", 2),
            EUR => ("Euro", "Europe", "🇪🇺", 2),
            FJD => ("Fiji dollar", "Fiji", "🇫🇯", 2),
            GBP => ("Pound sterling", "United Kingdom", "🇬🇧", 2),
            GEL => ("Georgian lari", "Georgia", "🇬🇪", 2),
            GHS => ("Ghanaian cedi", "Ghana", "🇬🇭", 2),
            GTQ => ("Guatemalan quetzal", "Guatemala", "🇬🇹", 2),
            HKD => ("Hong Kong dollar", "Hong Kong", "🇭🇰", 2),
            HNL => ("Honduran lempira", "Honduras", "🇭🇳", 2),
            HUF => ("Hungarian forint", "Hungary", "🇭🇺", 2),
            IDR => ("Indonesian rupiah", "Indonesia", "🇮🇩", 2),
            ILS => ("Israeli new shekel", "Israel", "🇮🇱", 2),
            INR => ("Indian rupee", "India", "🇮🇳", 2),
            IQD => ("Iraqi dinar", "Iraq", "🇮🇶", 3),
            ISK => ("Icelandic króna", "Iceland", "🇮🇸", 0),
            JMD => ("Jamaican dollar", "Jamaica", "🇯🇲", 2),
            JOD => ("Jordanian dinar", "Jordan", "🇯🇴", 3),
            JPY => ("Japanese yen", "Japan", "🇯🇵", 0),
            KES => ("Kenyan shilling", "Kenya", "🇰🇪", 2),
            KRW => ("South Korean won", "South Korea", "🇰🇷", 0),
            KWD => ("Kuwaiti dinar", "Kuwait", "🇰🇼", 3),
            KYD => ("Cayman Islands dollar", "Cayman Islands", "🇰🇾", 2),
            KZT => ("Kazakhstani tenge", "Kazakhstan", "🇰🇿", 2),
            LBP => ("Lebanese pound", "Lebanon", "🇱🇧", 0),
            LKR => ("Sri Lankan rupee", "Sri Lanka", "🇱🇰", 2),
            LYD => ("Libyan dinar", "Libya", "🇱🇾", 3),
            MAD => ("Moroccan dirham", "Morocco", "🇲🇦", 2),
            MDL => ("Moldovan leu", "Moldova", "🇲🇩", 2),
            MKD => ("Macedonian denar", "North Macedonia", "🇲🇰", 0),
            MNT => ("Mongolian tugrik", "Mongolia", "🇲🇳", 2),
            MOP => ("Macanese pataca", "Macau", "🇲🇴", 2),
            MUR => ("Mauritian rupee", "Mauritius", "🇲🇺", 2),
            MVR => ("Maldivian rufiyaa", "Maldives", "🇲🇻", 2),
            MXN => ("Mexican peso", "Mexico", "🇲🇽", 2),
            MYR => ("Malaysian ringgit", "Malaysia", "🇲🇾", 2),
            MZN => ("Mozambican metical", "Mozambique", "🇲🇿", 2),
            NAD => ("Namibian dollar", "Namibia", "🇳🇦", 2),
            NGN => ("Nigerian naira", "Nigeria", "🇳🇬", 2),
            NIO => ("Nicaraguan córdoba", "Nicaragua", "🇳🇮", 2),
            NOK => ("Norwegian krone", "Norway", "🇳🇴", 2),
            NPR => ("Nepalese rupee", "Nepal", "🇳🇵", 2),
            NZD => ("New Zealand dollar", "New Zealand", "🇳🇿", 2),
            OMR => ("Omani rial", "Oman", "🇴🇲", 3),
            PEN => ("Peruvian nuevo sol", "Peru", "🇵🇪", 2),
            PGK => ("Papua New Guinean kina", "Papua New Guinea", "🇵🇬", 2),
            PHP => ("Philippine peso", "Philippines", "🇵🇭", 2),
            PKR => ("Pakistani rupee", "Pakistan", "🇵🇰", 2),
            PLN => ("Polish złoty", "Poland", "🇵🇱", 2),
            PYG => ("Paraguayan guaraní", "Paraguay", "🇵🇾", 0),
            QAR => ("Qatari riyal", "Qatar", "🇶🇦", 2),
            RON => ("Romanian new leu", "Romania", "🇷🇴", 2),
            RSD => ("Serbian dinar", "Serbia", "🇷🇸", 2),
            RUB => ("Russian rouble", "Russia", "🇷🇺", 2),
            RWF => ("Rwandan franc", "Rwanda", "🇷🇼", 0),
            SAR => ("Saudi riyal", "Saudi Arabia", "🇸🇦", 2),
            SCR => ("Seychelles rupee", "Seychelles", "🇸🇨", 2),
            SEK => ("Swedish krona", "Sweden", "🇸🇪", 2),
            SGD => ("Singapore dollar", "Singapore", "🇸🇬", 2),
            SRD => ("Surinamese dollar", "Suriname", "🇸🇷", 2),
            THB => ("Thai baht", "Thailand", "🇹🇭", 2),
            TND => ("Tunisian dinar", "Tunisia", "🇹🇳", 3),
            TRY => ("Turkish lira", "Turkey", "🇹🇷", 2),
            TTD => ("Trinidad and Tobago dollar", "Trinidad and Tobago", "🇹🇹", 2),
            TWD => ("New Taiwan dollar", "Taiwan", "🇹🇼", 2),
            TZS => ("Tanzanian shilling", "Tanzania", "🇹🇿", 2),
            UAH => ("Ukrainian hryvnia", "Ukraine", "🇺🇦", 2),
            UGX => ("Ugandan shilling", "Uganda", "🇺🇬", 2),
            USD => ("United States dollar", "United States", "🇺🇸", 2),
            UYU => ("Uruguayan peso", "Uruguay", "🇺🇾", 2),
            UZS => ("Uzbekistan som", "Uzbekistan", "🇺🇿", 2),
            VND => ("Vietnamese dong", "Vietnam", "🇻🇳", 0),
            YER => ("Yemeni rial", "Yemen", "🇾🇪", 2),
            ZAR => ("South African rand", "South Africa", "🇿🇦", 2),
            ZMW => ("Zambian kwacha", "Zambia", "🇿🇲", 2),
        }
    }

    pub fn name(&self) -> &'static str {
        self.data().0
    }
    pub fn country(&self) -> &'static str {
        self.data().1
    }
    pub fn flag(&self) -> &'static str {
        self.data().2
    }
    pub fn decimals(&self) -> u8 {
        self.data().3
    }
}
