"""Backtide.

Author: Mavs
Description: ETF listings.

"""

# Major ETF traded worldwide available in yahoo finance
ETFS = [
    # ── US BROAD MARKET ──────────────────────────────────────────────────────
    {"ticker": "SPY", "name": "SPDR S&P 500", "currency": "USD"},
    {"ticker": "IVV", "name": "iShares Core S&P 500", "currency": "USD"},
    {"ticker": "VOO", "name": "Vanguard S&P 500", "currency": "USD"},
    {
        "ticker": "SPLG",
        "name": "SPDR Portfolio S&P 500",
        "currency": "USD",
    },
    {"ticker": "QQQ", "name": "Invesco QQQ (Nasdaq-100)", "currency": "USD"},
    {"ticker": "VTI", "name": "Vanguard Total Stock Market", "currency": "USD"},
    {
        "ticker": "SPTM",
        "name": "SPDR Portfolio S&P 1500 Composite Stock Market",
        "currency": "USD",
    },
    {"ticker": "IWM", "name": "iShares Russell 2000", "currency": "USD"},
    {"ticker": "DIA", "name": "SPDR Dow Jones Industrial Average", "currency": "USD"},
    {"ticker": "MDY", "name": "SPDR S&P MidCap 400", "currency": "USD"},
    {"ticker": "IJH", "name": "iShares Core S&P Mid-Cap", "currency": "USD"},
    {"ticker": "IJR", "name": "iShares Core S&P Small-Cap", "currency": "USD"},
    {"ticker": "ITOT", "name": "iShares Core S&P Total US Stock Market", "currency": "USD"},
    {"ticker": "SCHB", "name": "Schwab US Broad Market", "currency": "USD"},
    {"ticker": "VXF", "name": "Vanguard Extended Market", "currency": "USD"},
    {"ticker": "IWB", "name": "iShares Russell 1000", "currency": "USD"},
    {"ticker": "IWF", "name": "iShares Russell 1000 Growth", "currency": "USD"},
    {"ticker": "IWD", "name": "iShares Russell 1000 Value", "currency": "USD"},
    {"ticker": "SPYG", "name": "SPDR Portfolio S&P 500 Growth", "currency": "USD"},
    {"ticker": "SPYV", "name": "SPDR Portfolio S&P 500 Value", "currency": "USD"},
    {"ticker": "IVW", "name": "iShares S&P 500 Growth", "currency": "USD"},
    {"ticker": "IVE", "name": "iShares S&P 500 Value", "currency": "USD"},
    {"ticker": "VUG", "name": "Vanguard Growth", "currency": "USD"},
    {"ticker": "VTV", "name": "Vanguard Value", "currency": "USD"},
    {"ticker": "SCHX", "name": "Schwab US Large-Cap", "currency": "USD"},
    {"ticker": "SCHA", "name": "Schwab US Small-Cap", "currency": "USD"},
    {"ticker": "VB", "name": "Vanguard Small-Cap", "currency": "USD"},
    {"ticker": "VO", "name": "Vanguard Mid-Cap", "currency": "USD"},
    {"ticker": "VIOV", "name": "Vanguard S&P Small-Cap 600 Value", "currency": "USD"},
    {"ticker": "VIOG", "name": "Vanguard S&P Small-Cap 600 Growth", "currency": "USD"},
    {"ticker": "VBR", "name": "Vanguard Small-Cap Value", "currency": "USD"},
    {"ticker": "VBK", "name": "Vanguard Small-Cap Growth", "currency": "USD"},
    {"ticker": "SCHG", "name": "Schwab US Large-Cap Growth", "currency": "USD"},
    {"ticker": "SCHV", "name": "Schwab US Large-Cap Value", "currency": "USD"},
    {"ticker": "SCHM", "name": "Schwab US Mid-Cap", "currency": "USD"},
    {
        "ticker": "AVUV",
        "name": "Avantis US Small Cap Value",
        "currency": "USD",
    },
    {
        "ticker": "COWZ",
        "name": "Pacer US Cash Cows 100",
        "currency": "USD",
    },
    {"ticker": "CALF", "name": "Pacer US Small Cap Cash Cows 100", "currency": "USD"},
    # ── US SECTORS ────────────────────────────────────────────────────────────
    {"ticker": "XLF", "name": "Financial Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLK", "name": "Technology Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLE", "name": "Energy Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLV", "name": "Health Care Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLI", "name": "Industrial Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLY", "name": "Consumer Discretionary Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLP", "name": "Consumer Staples Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLU", "name": "Utilities Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLB", "name": "Materials Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLRE", "name": "Real Estate Select Sector SPDR", "currency": "USD"},
    {"ticker": "XLC", "name": "Communication Services Select Sector SPDR", "currency": "USD"},
    {"ticker": "VGT", "name": "Vanguard Information Technology", "currency": "USD"},
    {"ticker": "VHT", "name": "Vanguard Health Care", "currency": "USD"},
    {"ticker": "VFH", "name": "Vanguard Financials", "currency": "USD"},
    {"ticker": "VDE", "name": "Vanguard Energy", "currency": "USD"},
    {"ticker": "VIS", "name": "Vanguard Industrials", "currency": "USD"},
    {"ticker": "VAW", "name": "Vanguard Materials", "currency": "USD"},
    {"ticker": "VCR", "name": "Vanguard Consumer Discretionary", "currency": "USD"},
    {"ticker": "VDC", "name": "Vanguard Consumer Staples", "currency": "USD"},
    {"ticker": "VPU", "name": "Vanguard Utilities", "currency": "USD"},
    {"ticker": "VNQ", "name": "Vanguard Real Estate", "currency": "USD"},
    {"ticker": "SOXX", "name": "iShares Semiconductor", "currency": "USD"},
    {"ticker": "SMH", "name": "VanEck Semiconductor", "currency": "USD"},
    {"ticker": "IBB", "name": "iShares Biotechnology", "currency": "USD"},
    {"ticker": "XBI", "name": "SPDR S&P Biotech", "currency": "USD"},
    {"ticker": "IYR", "name": "iShares US Real Estate", "currency": "USD"},
    {"ticker": "KRE", "name": "SPDR S&P Regional Banking", "currency": "USD"},
    {"ticker": "KBE", "name": "SPDR S&P Bank", "currency": "USD"},
    {"ticker": "XHB", "name": "SPDR S&P Homebuilders", "currency": "USD"},
    {"ticker": "ITB", "name": "iShares US Home Construction", "currency": "USD"},
    {"ticker": "HACK", "name": "ETFMG Prime Cyber Security", "currency": "USD"},
    {"ticker": "CIBR", "name": "First Trust NASDAQ Cybersecurity", "currency": "USD"},
    {"ticker": "ROBO", "name": "Robo Global Robotics and Automation", "currency": "USD"},
    {"ticker": "BOTZ", "name": "Global X Robotics & Artificial Intelligence", "currency": "USD"},
    {"ticker": "CLOU", "name": "Global X Cloud Computing", "currency": "USD"},
    {"ticker": "FINX", "name": "Global X FinTech", "currency": "USD"},
    {"ticker": "DRIV", "name": "Global X Autonomous & Electric Vehicles", "currency": "USD"},
    {"ticker": "LIT", "name": "Global X Lithium & Battery Tech", "currency": "USD"},
    {"ticker": "ICLN", "name": "iShares Global Clean Energy", "currency": "USD"},
    {"ticker": "TAN", "name": "Invesco Solar", "currency": "USD"},
    {"ticker": "FAN", "name": "First Trust Global Wind Energy", "currency": "USD"},
    {"ticker": "JETS", "name": "US Global Jets", "currency": "USD"},
    {"ticker": "MOO", "name": "VanEck Agribusiness", "currency": "USD"},
    {
        "ticker": "MLPX",
        "name": "Global X MLP & Energy Infrastructure (corp-structured, no K-1)",
        "currency": "USD",
    },  # ★ replaces AMLP/MLPA
    {
        "ticker": "ENFR",
        "name": "Alerian Energy Infrastructure (no K-1)",
        "currency": "USD",
    },  # ★ replaces MLPA
    # ── LEVERAGED / INVERSE ───────────────────────────────────────────────────
    {"ticker": "TQQQ", "name": "ProShares UltraPro QQQ (3x)", "currency": "USD"},
    {"ticker": "SQQQ", "name": "ProShares UltraPro Short QQQ (-3x)", "currency": "USD"},
    {"ticker": "UPRO", "name": "ProShares UltraPro S&P500 (3x)", "currency": "USD"},
    {"ticker": "SPXU", "name": "ProShares UltraPro Short S&P500 (-3x)", "currency": "USD"},
    {"ticker": "SPXS", "name": "Direxion Daily S&P 500 Bear 3X", "currency": "USD"},
    {"ticker": "SSO", "name": "ProShares Ultra S&P500 (2x)", "currency": "USD"},
    {"ticker": "SDS", "name": "ProShares UltraShort S&P500 (-2x)", "currency": "USD"},
    {"ticker": "SH", "name": "ProShares Short S&P500 (-1x)", "currency": "USD"},
    {"ticker": "QLD", "name": "ProShares Ultra QQQ (2x)", "currency": "USD"},
    {"ticker": "QID", "name": "ProShares UltraShort QQQ (-2x)", "currency": "USD"},
    {"ticker": "PSQ", "name": "ProShares Short QQQ (-1x)", "currency": "USD"},
    {"ticker": "UDOW", "name": "ProShares UltraPro Dow30 (3x)", "currency": "USD"},
    {"ticker": "SDOW", "name": "ProShares UltraPro Short Dow30 (-3x)", "currency": "USD"},
    {"ticker": "DOG", "name": "ProShares Short Dow30 (-1x)", "currency": "USD"},
    {"ticker": "TNA", "name": "Direxion Daily Small Cap Bull 3X", "currency": "USD"},
    {"ticker": "TZA", "name": "Direxion Daily Small Cap Bear 3X", "currency": "USD"},
    {"ticker": "SOXL", "name": "Direxion Daily Semiconductor Bull 3X", "currency": "USD"},
    {"ticker": "SOXS", "name": "Direxion Daily Semiconductor Bear 3X", "currency": "USD"},
    {"ticker": "FAS", "name": "Direxion Daily Financial Bull 3X", "currency": "USD"},
    {"ticker": "FAZ", "name": "Direxion Daily Financial Bear 3X", "currency": "USD"},
    {"ticker": "ERX", "name": "Direxion Daily Energy Bull 2X", "currency": "USD"},
    {"ticker": "ERY", "name": "Direxion Daily Energy Bear 2X", "currency": "USD"},
    {"ticker": "LABU", "name": "Direxion Daily S&P Biotech Bull 3X", "currency": "USD"},
    {"ticker": "LABD", "name": "Direxion Daily S&P Biotech Bear 3X", "currency": "USD"},
    {"ticker": "NUGT", "name": "Direxion Daily Gold Miners Bull 2X", "currency": "USD"},
    {"ticker": "DUST", "name": "Direxion Daily Gold Miners Bear 2X", "currency": "USD"},
    {"ticker": "GDXJ", "name": "VanEck Junior Gold Miners", "currency": "USD"},
    {"ticker": "UVXY", "name": "ProShares Ultra VIX Short-Term Futures", "currency": "USD"},
    {"ticker": "SVXY", "name": "ProShares Short VIX Short-Term Futures", "currency": "USD"},
    {"ticker": "VIXY", "name": "ProShares VIX Short-Term Futures", "currency": "USD"},
    # ── FIXED INCOME ─────────────────────────────────────────────────────────
    {"ticker": "AGG", "name": "iShares Core US Aggregate Bond", "currency": "USD"},
    {"ticker": "BND", "name": "Vanguard Total Bond Market", "currency": "USD"},
    {"ticker": "TLT", "name": "iShares 20+ Year Treasury Bond", "currency": "USD"},
    {"ticker": "IEF", "name": "iShares 7-10 Year Treasury Bond", "currency": "USD"},
    {"ticker": "SHY", "name": "iShares 1-3 Year Treasury Bond", "currency": "USD"},
    {"ticker": "GOVT", "name": "iShares US Treasury Bond", "currency": "USD"},
    {"ticker": "TIPS", "name": "iShares TIPS Bond", "currency": "USD"},
    {"ticker": "HYG", "name": "iShares iBoxx $ High Yield Corporate Bond", "currency": "USD"},
    {"ticker": "JNK", "name": "SPDR Bloomberg High Yield Bond", "currency": "USD"},
    {"ticker": "LQD", "name": "iShares iBoxx $ Investment Grade Corporate", "currency": "USD"},
    {"ticker": "VCIT", "name": "Vanguard Intermediate-Term Corporate Bond", "currency": "USD"},
    {"ticker": "VCSH", "name": "Vanguard Short-Term Corporate Bond", "currency": "USD"},
    {"ticker": "VGLT", "name": "Vanguard Long-Term Treasury", "currency": "USD"},
    {"ticker": "MUB", "name": "iShares National Muni Bond", "currency": "USD"},
    {"ticker": "EMB", "name": "iShares JP Morgan USD Emerging Markets Bond", "currency": "USD"},
    {"ticker": "BNDX", "name": "Vanguard Total International Bond", "currency": "USD"},
    {"ticker": "FLOT", "name": "iShares Floating Rate Bond", "currency": "USD"},
    {"ticker": "BSV", "name": "Vanguard Short-Term Bond", "currency": "USD"},
    {"ticker": "BIV", "name": "Vanguard Intermediate-Term Bond", "currency": "USD"},
    {"ticker": "BLV", "name": "Vanguard Long-Term Bond", "currency": "USD"},
    {"ticker": "SCHZ", "name": "Schwab US Aggregate Bond", "currency": "USD"},
    {"ticker": "SPAB", "name": "SPDR Portfolio Aggregate Bond", "currency": "USD"},
    {"ticker": "TBF", "name": "ProShares Short 20+ Year Treasury", "currency": "USD"},
    {"ticker": "TMF", "name": "Direxion Daily 20+ Year Treasury Bull 3X", "currency": "USD"},
    {"ticker": "TMV", "name": "Direxion Daily 20+ Year Treasury Bear 3X", "currency": "USD"},
    {"ticker": "SHV", "name": "iShares Short Treasury Bond", "currency": "USD"},
    {"ticker": "BIL", "name": "SPDR Bloomberg 1-3 Month T-Bill", "currency": "USD"},
    {"ticker": "SGOV", "name": "iShares 0-3 Month Treasury Bond", "currency": "USD"},
    {"ticker": "TBIL", "name": "US Treasury 3 Month Bill", "currency": "USD"},
    {"ticker": "IGSB", "name": "iShares Short-Term Corporate Bond", "currency": "USD"},
    {"ticker": "IGIB", "name": "iShares Intermediate-Term Corporate Bond", "currency": "USD"},
    {"ticker": "IGLB", "name": "iShares Long-Term Corporate Bond", "currency": "USD"},
    {"ticker": "SHYG", "name": "iShares 0-5 Year High Yield Corporate Bond", "currency": "USD"},
    {"ticker": "USHY", "name": "iShares Broad USD High Yield Corporate Bond", "currency": "USD"},
    {"ticker": "ANGL", "name": "VanEck Fallen Angel High Yield Bond", "currency": "USD"},
    {"ticker": "FALN", "name": "iShares Fallen Angels USD Bond", "currency": "USD"},
    {"ticker": "BKLN", "name": "Invesco Senior Loan", "currency": "USD"},
    {"ticker": "SRLN", "name": "SPDR Blackstone Senior Loan", "currency": "USD"},
    {"ticker": "VCLT", "name": "Vanguard Long-Term Corporate Bond", "currency": "USD"},
    {"ticker": "MINT", "name": "PIMCO Enhanced Short Maturity Active", "currency": "USD"},
    {"ticker": "TOTL", "name": "SPDR DoubleLine Total Return Tactical", "currency": "USD"},
    {"ticker": "BOND", "name": "PIMCO Active Bond", "currency": "USD"},
    {"ticker": "NEAR", "name": "iShares Short Maturity Bond", "currency": "USD"},
    {"ticker": "HYDB", "name": "iShares High Yield Bond Factor", "currency": "USD"},
    {"ticker": "VTIP", "name": "Vanguard Short-Term Inflation-Protected Sec", "currency": "USD"},
    {"ticker": "STIP", "name": "iShares 0-5 Year TIPS Bond", "currency": "USD"},
    {"ticker": "QLTA", "name": "iShares Aaa - A Rated Corporate Bond", "currency": "USD"},
    {
        "ticker": "GIGB",
        "name": "Goldman Sachs Access Investment Grade Corp Bond",
        "currency": "USD",
    },
    {"ticker": "GHYB", "name": "Goldman Sachs Access High Yield Corp Bond", "currency": "USD"},
    {"ticker": "PCY", "name": "Invesco Emerging Markets Sovereign Debt", "currency": "USD"},
    {"ticker": "LEMB", "name": "iShares J.P. Morgan EM Local Currency Bond", "currency": "USD"},
    {"ticker": "EBND", "name": "SPDR Bloomberg Emerging Markets Local Bond", "currency": "USD"},
    {"ticker": "IAGG", "name": "iShares Core International Aggregate Bond", "currency": "USD"},
    {"ticker": "BWX", "name": "SPDR Bloomberg International Treasury Bond", "currency": "USD"},
    {
        "ticker": "WIP",
        "name": "SPDR FTSE International Gov Inflation-Protected Bond",
        "currency": "USD",
    },
    {"ticker": "HYEM", "name": "VanEck Emerging Markets High Yield Bond", "currency": "USD"},
    {"ticker": "SCHI", "name": "Schwab 5-10 Year Corporate Bond", "currency": "USD"},
    {"ticker": "SCHR", "name": "Schwab Intermediate-Term US Treasury", "currency": "USD"},
    {"ticker": "SCHO", "name": "Schwab Short-Term US Treasury", "currency": "USD"},
    {"ticker": "SCHP", "name": "Schwab US TIPS", "currency": "USD"},
    # ── COMMODITIES ───────────────────────────────────────────────────────────
    {"ticker": "GLD", "name": "SPDR Gold", "currency": "USD"},
    {"ticker": "IAU", "name": "iShares Gold", "currency": "USD"},
    {"ticker": "GLDM", "name": "SPDR Gold MiniShares", "currency": "USD"},
    {"ticker": "SLV", "name": "iShares Silver", "currency": "USD"},
    {"ticker": "SIVR", "name": "Aberdeen Standard Physical Silver", "currency": "USD"},
    {"ticker": "GDX", "name": "VanEck Gold Miners", "currency": "USD"},
    {"ticker": "PPLT", "name": "Aberdeen Standard Physical Platinum", "currency": "USD"},
    {"ticker": "PALL", "name": "Aberdeen Standard Physical Palladium", "currency": "USD"},
    {"ticker": "CPER", "name": "United States Copper", "currency": "USD"},
    {"ticker": "USO", "name": "United States Oil", "currency": "USD"},
    {"ticker": "BNO", "name": "United States Brent Oil", "currency": "USD"},
    {"ticker": "UNG", "name": "United States Natural Gas", "currency": "USD"},
    {"ticker": "DBC", "name": "Invesco DB Commodity Tracking", "currency": "USD"},
    {"ticker": "PDBC", "name": "Invesco Optimum Yield Diversified Commodity", "currency": "USD"},
    {"ticker": "GSG", "name": "iShares S&P GSCI Commodity-Indexed", "currency": "USD"},
    {"ticker": "DBA", "name": "Invesco DB Agriculture", "currency": "USD"},
    {"ticker": "DBB", "name": "Invesco DB Base Metals", "currency": "USD"},
    {"ticker": "DBO", "name": "Invesco DB Oil", "currency": "USD"},
    {"ticker": "WEAT", "name": "Teucrium Wheat", "currency": "USD"},
    {"ticker": "CORN", "name": "Teucrium Corn", "currency": "USD"},
    {"ticker": "SOYB", "name": "Teucrium Soybean", "currency": "USD"},
    {"ticker": "UGA", "name": "United States Gasoline", "currency": "USD"},
    # ── INTERNATIONAL / GLOBAL ───────────────────────────────────────────────
    {"ticker": "EEM", "name": "iShares MSCI Emerging Markets", "currency": "USD"},
    {"ticker": "VWO", "name": "Vanguard FTSE Emerging Markets", "currency": "USD"},
    {"ticker": "EFA", "name": "iShares MSCI EAFE", "currency": "USD"},
    {"ticker": "VEA", "name": "Vanguard FTSE Developed Markets", "currency": "USD"},
    {"ticker": "IEFA", "name": "iShares Core MSCI EAFE", "currency": "USD"},
    {"ticker": "IEMG", "name": "iShares Core MSCI Emerging Markets", "currency": "USD"},
    {"ticker": "VT", "name": "Vanguard Total World Stock", "currency": "USD"},
    {"ticker": "ACWI", "name": "iShares MSCI ACWI", "currency": "USD"},
    {"ticker": "VXUS", "name": "Vanguard Total International Stock", "currency": "USD"},
    {"ticker": "IXUS", "name": "iShares Core MSCI Total International Stock", "currency": "USD"},
    {"ticker": "SPDW", "name": "SPDR Portfolio Developed World ex-US", "currency": "USD"},
    {"ticker": "SPEM", "name": "SPDR Portfolio Emerging Markets", "currency": "USD"},
    {
        "ticker": "EMXC",
        "name": "iShares MSCI Emerging Markets ex China",
        "currency": "USD",
    },
    {"ticker": "EWJ", "name": "iShares MSCI Japan", "currency": "USD"},
    {"ticker": "EWZ", "name": "iShares MSCI Brazil", "currency": "USD"},
    {"ticker": "EWG", "name": "iShares MSCI Germany", "currency": "USD"},
    {"ticker": "EWU", "name": "iShares MSCI United Kingdom", "currency": "USD"},
    {"ticker": "EWC", "name": "iShares MSCI Canada", "currency": "USD"},
    {"ticker": "EWA", "name": "iShares MSCI Australia", "currency": "USD"},
    {"ticker": "EWH", "name": "iShares MSCI Hong Kong", "currency": "USD"},
    {"ticker": "EWY", "name": "iShares MSCI South Korea", "currency": "USD"},
    {"ticker": "EWT", "name": "iShares MSCI Taiwan", "currency": "USD"},
    {"ticker": "EWI", "name": "iShares MSCI Italy", "currency": "USD"},
    {"ticker": "EWP", "name": "iShares MSCI Spain", "currency": "USD"},
    {"ticker": "EWQ", "name": "iShares MSCI France", "currency": "USD"},
    {"ticker": "EWL", "name": "iShares MSCI Switzerland", "currency": "USD"},
    {"ticker": "EWN", "name": "iShares MSCI Netherlands", "currency": "USD"},
    {"ticker": "EWS", "name": "iShares MSCI Singapore", "currency": "USD"},
    {"ticker": "EWM", "name": "iShares MSCI Malaysia", "currency": "USD"},
    {"ticker": "EWW", "name": "iShares MSCI Mexico", "currency": "USD"},
    {"ticker": "EWX", "name": "SPDR S&P Emerging Markets Small Cap", "currency": "USD"},
    {"ticker": "FXI", "name": "iShares China Large-Cap", "currency": "USD"},
    {"ticker": "MCHI", "name": "iShares MSCI China", "currency": "USD"},
    {"ticker": "CQQQ", "name": "Invesco China Technology", "currency": "USD"},
    {"ticker": "KWEB", "name": "KraneShares CSI China Internet", "currency": "USD"},
    {"ticker": "INDA", "name": "iShares MSCI India", "currency": "USD"},
    {"ticker": "INDY", "name": "iShares India 50", "currency": "USD"},
    {"ticker": "PIN", "name": "Invesco India", "currency": "USD"},
    {"ticker": "EIDO", "name": "iShares MSCI Indonesia", "currency": "USD"},
    {"ticker": "THD", "name": "iShares MSCI Thailand", "currency": "USD"},
    {"ticker": "ECH", "name": "iShares MSCI Chile", "currency": "USD"},
    {"ticker": "EWO", "name": "iShares MSCI Austria", "currency": "USD"},
    {"ticker": "GXC", "name": "SPDR S&P China", "currency": "USD"},
    {"ticker": "ASHR", "name": "Xtrackers Harvest CSI 300 China A", "currency": "USD"},
    {"ticker": "DXJ", "name": "WisdomTree Japan Hedged Equity", "currency": "USD"},
    {"ticker": "HEDJ", "name": "WisdomTree Europe Hedged Equity", "currency": "USD"},
    {
        "ticker": "AVDV",
        "name": "Avantis International Small Cap Value",
        "currency": "USD",
    },
    {"ticker": "FNDF", "name": "Schwab Fundamental International Large Co.", "currency": "USD"},
    {"ticker": "FNDE", "name": "Schwab Fundamental EM Large Co.", "currency": "USD"},
    {"ticker": "FNDX", "name": "Schwab Fundamental US Large Co.", "currency": "USD"},
    {"ticker": "SCHF", "name": "Schwab International Equity", "currency": "USD"},
    {"ticker": "SCHE", "name": "Schwab Emerging Markets Equity", "currency": "USD"},
    # ── DIVIDEND / INCOME ─────────────────────────────────────────────────────
    {"ticker": "VYM", "name": "Vanguard High Dividend Yield", "currency": "USD"},
    {"ticker": "DVY", "name": "iShares Select Dividend", "currency": "USD"},
    {"ticker": "HDV", "name": "iShares Core High Dividend", "currency": "USD"},
    {"ticker": "SCHD", "name": "Schwab US Dividend Equity", "currency": "USD"},
    {"ticker": "SDY", "name": "SPDR S&P Dividend", "currency": "USD"},
    {"ticker": "NOBL", "name": "ProShares S&P 500 Dividend Aristocrats", "currency": "USD"},
    {"ticker": "DGRO", "name": "iShares Core Dividend Growth", "currency": "USD"},
    {"ticker": "VIG", "name": "Vanguard Dividend Appreciation", "currency": "USD"},
    {"ticker": "DGRW", "name": "WisdomTree US Quality Dividend Growth", "currency": "USD"},
    {"ticker": "PFF", "name": "iShares Preferred & Income Securities", "currency": "USD"},
    {"ticker": "PFFD", "name": "Global X US Preferred", "currency": "USD"},
    # ── FACTOR / SMART BETA ──────────────────────────────────────────────────
    {"ticker": "MTUM", "name": "iShares MSCI USA Momentum Factor", "currency": "USD"},
    {"ticker": "VLUE", "name": "iShares MSCI USA Value Factor", "currency": "USD"},
    {"ticker": "QUAL", "name": "iShares MSCI USA Quality Factor", "currency": "USD"},
    {"ticker": "USMV", "name": "iShares MSCI USA Min Vol Factor", "currency": "USD"},
    {"ticker": "SIZE", "name": "iShares MSCI USA Size Factor", "currency": "USD"},
    {"ticker": "SPHQ", "name": "Invesco S&P 500 Quality", "currency": "USD"},
    {"ticker": "SPMO", "name": "Invesco S&P 500 Momentum", "currency": "USD"},
    {"ticker": "SPLV", "name": "Invesco S&P 500 Low Volatility", "currency": "USD"},
    {"ticker": "SPHD", "name": "Invesco S&P 500 High Dividend Low Volatility", "currency": "USD"},
    {"ticker": "ONEQ", "name": "Fidelity Nasdaq Composite", "currency": "USD"},
    # ── FIDELITY SECTOR ETFs ──────────────────────────────────────────────────
    {"ticker": "FTEC", "name": "Fidelity MSCI Information Technology", "currency": "USD"},
    {"ticker": "FHLC", "name": "Fidelity MSCI Health Care", "currency": "USD"},
    {"ticker": "FNCL", "name": "Fidelity MSCI Financials", "currency": "USD"},
    {"ticker": "FENY", "name": "Fidelity MSCI Energy", "currency": "USD"},
    {"ticker": "FIDU", "name": "Fidelity MSCI Industrials", "currency": "USD"},
    {"ticker": "FDIS", "name": "Fidelity MSCI Consumer Discretionary", "currency": "USD"},
    {"ticker": "FSTA", "name": "Fidelity MSCI Consumer Staples", "currency": "USD"},
    {"ticker": "FUTY", "name": "Fidelity MSCI Utilities", "currency": "USD"},
    {"ticker": "FREL", "name": "Fidelity MSCI Real Estate", "currency": "USD"},
    {"ticker": "FMAT", "name": "Fidelity MSCI Materials", "currency": "USD"},
    {"ticker": "FCOM", "name": "Fidelity MSCI Communication Services", "currency": "USD"},
    # ── CRYPTO / DIGITAL ASSETS ──────────────────────────────────────────────
    {"ticker": "BITO", "name": "ProShares Bitcoin Strategy", "currency": "USD"},
    {"ticker": "BITI", "name": "ProShares Short Bitcoin", "currency": "USD"},
    {"ticker": "BLOK", "name": "Amplify Transformational Data Sharing", "currency": "USD"},
    {"ticker": "BITB", "name": "Bitwise Bitcoin", "currency": "USD"},
    {"ticker": "FBTC", "name": "Fidelity Wise Origin Bitcoin", "currency": "USD"},
    {"ticker": "IBIT", "name": "iShares Bitcoin", "currency": "USD"},
    {"ticker": "GBTC", "name": "Grayscale Bitcoin", "currency": "USD"},
    # ── ESG ───────────────────────────────────────────────────────────────────
    {"ticker": "ESGU", "name": "iShares MSCI USA ESG Screened", "currency": "USD"},
    {"ticker": "SUSA", "name": "iShares MSCI USA ESG Select", "currency": "USD"},
    {"ticker": "ESGD", "name": "iShares MSCI EAFE ESG Screened", "currency": "USD"},
    {"ticker": "ESGE", "name": "iShares MSCI EM ESG Screened", "currency": "USD"},
    {"ticker": "VSGX", "name": "Vanguard ESG International Stock", "currency": "USD"},
    {"ticker": "ESGV", "name": "Vanguard ESG US Stock", "currency": "USD"},
    # ── THEMATIC ─────────────────────────────────────────────────────────────
    {"ticker": "ARKK", "name": "ARK Innovation", "currency": "USD"},
    {"ticker": "ARKG", "name": "ARK Genomic Revolution", "currency": "USD"},
    {"ticker": "ARKW", "name": "ARK Next Generation Internet", "currency": "USD"},
    {"ticker": "ARKF", "name": "ARK Fintech Innovation", "currency": "USD"},
    {"ticker": "ARKQ", "name": "ARK Autonomous Technology & Robotics", "currency": "USD"},
    {"ticker": "ARKE", "name": "ARK Space Exploration & Innovation", "currency": "USD"},
    {"ticker": "WCLD", "name": "WisdomTree Cloud Computing", "currency": "USD"},
    # ── EUROPEAN-LISTED ETFs (EUR / GBP) ─────────────────────────────────────
    {"ticker": "CSPX.L", "name": "iShares Core S&P 500 UCITS", "currency": "USD"},
    {"ticker": "VUSA.L", "name": "Vanguard S&P 500 UCITS", "currency": "USD"},
    {"ticker": "SWRD.L", "name": "SPDR MSCI World UCITS", "currency": "USD"},
    {"ticker": "IWDG.L", "name": "iShares Edge MSCI World Min Vol UCITS", "currency": "GBP"},
    {"ticker": "ISF.L", "name": "iShares Core FTSE 100 UCITS", "currency": "GBP"},
    {"ticker": "VWRL.L", "name": "Vanguard FTSE All-World UCITS", "currency": "USD"},
    {"ticker": "EMIM.L", "name": "iShares Core MSCI EM IMI UCITS", "currency": "USD"},
    {"ticker": "IWDA.L", "name": "iShares Core MSCI World UCITS", "currency": "USD"},
    {"ticker": "EIMI.L", "name": "iShares Core MSCI EM IMI UCITS USD", "currency": "USD"},
    {"ticker": "VAGP.L", "name": "Vanguard Global Aggregate Bond UCITS", "currency": "USD"},
    {"ticker": "IGLT.L", "name": "iShares Core UK Gilts UCITS", "currency": "GBP"},
    {"ticker": "SLXX.L", "name": "iShares Core £ Corp Bond UCITS", "currency": "GBP"},
    {"ticker": "SGLN.L", "name": "iShares Physical Gold ETC", "currency": "USD"},
    {"ticker": "PHAU.L", "name": "WisdomTree Physical Gold ETC", "currency": "USD"},
    {"ticker": "EXW1.DE", "name": "iShares Core MSCI World UCITS", "currency": "EUR"},
    {"ticker": "EXXT.DE", "name": "iShares Core MSCI EM IMI UCITS", "currency": "EUR"},
    {"ticker": "EXS1.DE", "name": "iShares Core DAX UCITS", "currency": "EUR"},
    {"ticker": "DBXD.DE", "name": "Xtrackers DAX UCITS", "currency": "EUR"},
    {"ticker": "ZPRS.DE", "name": "SPDR S&P 500 UCITS EUR Hedged", "currency": "EUR"},
    {"ticker": "XDWD.DE", "name": "Xtrackers MSCI World Swap UCITS", "currency": "EUR"},
    {"ticker": "LYPS.PA", "name": "Lyxor S&P 500 UCITS", "currency": "EUR"},
    {"ticker": "CW8.PA", "name": "Amundi MSCI World UCITS", "currency": "EUR"},
    {"ticker": "PAEEM.PA", "name": "Amundi MSCI Emerging Markets UCITS", "currency": "EUR"},
    {"ticker": "SMAE.PA", "name": "Lyxor CAC 40 UCITS", "currency": "EUR"},
    # ── CANADIAN-LISTED ETFs (CAD) ────────────────────────────────────────────
    {"ticker": "XIU.TO", "name": "iShares S&P/TSX 60", "currency": "CAD"},
    {"ticker": "XIC.TO", "name": "iShares Core S&P/TSX Capped Composite", "currency": "CAD"},
    {"ticker": "ZSP.TO", "name": "BMO S&P 500", "currency": "CAD"},
    {"ticker": "VFV.TO", "name": "Vanguard S&P 500", "currency": "CAD"},
    {"ticker": "XEQT.TO", "name": "iShares Core Equity Portfolio", "currency": "CAD"},
    {"ticker": "VEQT.TO", "name": "Vanguard All-Equity Portfolio", "currency": "CAD"},
    {"ticker": "XGRO.TO", "name": "iShares Core Growth Portfolio", "currency": "CAD"},
    {"ticker": "ZAG.TO", "name": "BMO Aggregate Bond", "currency": "CAD"},
    {"ticker": "XBB.TO", "name": "iShares Core Canadian Universe Bond", "currency": "CAD"},
    {"ticker": "HXT.TO", "name": "Horizons S&P/TSX 60", "currency": "CAD"},
    {"ticker": "HXS.TO", "name": "Horizons S&P 500", "currency": "CAD"},
    # ── AUSTRALIAN-LISTED ETFs (AUD) ──────────────────────────────────────────
    {"ticker": "VAS.AX", "name": "Vanguard Australian", "currency": "AUD"},
    {"ticker": "VGS.AX", "name": "Vanguard MSCI International", "currency": "AUD"},
    {"ticker": "A200.AX", "name": "BetaShares Australia 200", "currency": "AUD"},
    {"ticker": "NDQ.AX", "name": "BetaShares NASDAQ 100", "currency": "AUD"},
    {"ticker": "IOZ.AX", "name": "iShares Core S&P/ASX 200", "currency": "AUD"},
    {"ticker": "IVV.AX", "name": "iShares S&P 500", "currency": "AUD"},
    {"ticker": "STW.AX", "name": "SPDR S&P/ASX 200", "currency": "AUD"},
    {"ticker": "GOLD.AX", "name": "BetaShares Gold Bullion", "currency": "AUD"},
    {"ticker": "QOZ.AX", "name": "BetaShares FTSE RAFI Australia 200", "currency": "AUD"},
    {"ticker": "QUAL.AX", "name": "VanEck MSCI World ex-Aus Quality", "currency": "AUD"},
    # ── JAPAN-LISTED ETFs (JPY) ───────────────────────────────────────────────
    {"ticker": "1306.T", "name": "Nomura TOPIX", "currency": "JPY"},
    {"ticker": "1321.T", "name": "Nikkei 225 Nomura", "currency": "JPY"},
    {"ticker": "1330.T", "name": "Nikko AM Nikkei 225", "currency": "JPY"},
    {"ticker": "1570.T", "name": "Nomura Nikkei 225 Leveraged", "currency": "JPY"},
    {"ticker": "1357.T", "name": "Nomura Nikkei 225 Double Inverse", "currency": "JPY"},
    {"ticker": "2558.T", "name": "Blackrock iShares S&P 500 JPY", "currency": "JPY"},
    # ── HONG KONG / CHINA-LISTED ETFs (HKD) ──────────────────────────────────
    {"ticker": "2800.HK", "name": "Tracker of Hong Kong", "currency": "HKD"},
    {"ticker": "2823.HK", "name": "iShares A50 China", "currency": "HKD"},
    {"ticker": "3140.HK", "name": "ChinaAMC CSI 300", "currency": "HKD"},
    {"ticker": "2846.HK", "name": "SPDR S&P 500", "currency": "HKD"},
    # ── SINGAPORE-LISTED ETFs (SGD) ───────────────────────────────────────────
    {"ticker": "ES3.SI", "name": "SPDR Straits Times", "currency": "SGD"},
    {"ticker": "CLR.SI", "name": "iShares Core MSCI Asia ex Japan IMI", "currency": "USD"},
]
