name: Linting and tests

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

env:
  UV_VERSION: "0.11.7"
  PYTHON_VERSION: "3.14"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - run: |
          uv sync --group tox
          uv run tox -e pre-commit

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - name: Run tests
        run: |
          uv sync --group tox
          uv run tox -m unit
      - uses: codecov/codecov-action@v4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          files: ./coverage.xml

  cargo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - name: Set Python library path
        run: echo "LD_LIBRARY_PATH=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')" >> "$GITHUB_ENV"
      - name: Run Cargo tests
        run: |
          uv sync --group tox
          uv run tox -e cargo-test

  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - name: Set Python library path
        run: echo "LD_LIBRARY_PATH=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')" >> "$GITHUB_ENV"
      - name: Run benchmarks
        run: |
          uv sync --group tox
          uv run tox -e bench

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - run: |
          uv sync --group tox
          uv run tox -e docs
