name: Linting and tests

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

env:
  PYTHON_VERSION: "3.14"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{ runner.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock', 'tox.ini') }}
          restore-keys: |
            tox-${{ runner.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - run: |
          uv run --no-default-groups --group tox tox -e pre-commit

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      UV_LOCK_TIMEOUT: "1200"
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{ matrix.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock', 'tox.ini') }}
          restore-keys: |
            tox-${{ matrix.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - name: Run tests
        run: |
          uv run --no-default-groups --group tox tox -m unit -p auto --parallel-no-spinner
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tvdboom/backtide
          files: ./coverage.xml

  cargo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{ runner.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock', 'tox.ini') }}
          restore-keys: |
            tox-${{ runner.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - name: Set Python library path
        run: echo "LD_LIBRARY_PATH=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')" >> "$GITHUB_ENV"
      - name: Run Cargo tests
        run: |
          uv run --no-default-groups --group tox tox -e cargo-test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tvdboom/backtide
          files: ./rust-coverage.info

  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{ runner.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock', 'tox.ini') }}
          restore-keys: |
            tox-${{ runner.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - name: Set Python library path
        run: echo "LD_LIBRARY_PATH=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')" >> "$GITHUB_ENV"
      - name: Run benchmarks
        run: |
          uv run --no-default-groups --group tox tox -e bench

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - uses: actions/cache@v4
        with:
          path: .tox
          key: tox-${{ runner.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock', 'tox.ini') }}
          restore-keys: |
            tox-${{ runner.os }}-${{ github.job }}-py${{ env.PYTHON_VERSION }}-
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/backtide_core
      - run: |
          uv run --no-default-groups --group tox tox -e docs
